# Generated by Django 2.2.4 on 2019-09-26 01:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Teatro',
                'verbose_name_plural': 'Teatros',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_evento', models.DateTimeField(verbose_name='Data do Show')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do ingresso')),
                ('quantidade_lugares', models.PositiveIntegerField(verbose_name='Quantidade máxima')),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Cancelado')], default=1, verbose_name='Status')),
                ('teatro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='eventos.Teatro')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ('data_evento',),
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Máximo de 16 caracteres. Deixe em branco para gerar automáticamente.', max_length=16, null=True, verbose_name='Codigo do Ingresso')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido?')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingressos', to='eventos.Show')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
            },
        ),
    ]
