# Generated by Django 2.2.4 on 2019-09-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Teatro',
                'verbose_name_plural': 'Teatros',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_evento', models.DateTimeField(verbose_name='Data do Show')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do ingresso')),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Cancelado')], verbose_name='Status')),
                ('teatro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Teatro')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, verbose_name='Codigo do Ingresso')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido?')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.Show')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
            },
        ),
    ]
