# Generated by Django 2.2.4 on 2019-09-18 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('data_evento',), 'verbose_name': 'Show', 'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterModelOptions(
            name='teatro',
            options={'ordering': ('nome',), 'verbose_name': 'Teatro', 'verbose_name_plural': 'Teatros'},
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show', to='eventos.Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Cancelado')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='show',
            name='teatro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teatro', to='eventos.Teatro'),
        ),
    ]
