# Generated by Django 2.2.4 on 2019-09-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20190917_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo do Ingresso'),
        ),
    ]
