# Generated by Django 2.2.4 on 2019-09-22 02:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20190919_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingressos', to='eventos.Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='teatro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='eventos.Teatro'),
        ),
        migrations.AlterField(
            model_name='show',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do ingresso'),
        ),
    ]
