# Generated by Django 2.2.4 on 2019-09-25 03:03

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20190921_2304'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='vendas',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='eventos.Show'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendas',
            name='ingresso',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='show', chained_model_field='show', on_delete=django.db.models.deletion.CASCADE, to='eventos.Ingresso'),
        ),
    ]
