# Generated by Django 2.2.4 on 2019-09-25 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20190925_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='show',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.Ingresso'),
        ),
    ]
